server:
  port: 20001
spring:
  application:
    name: eureka-server  #配置微服务的名称,以后所有的微服务,都必须配置这个属性,不然eureka注册中心的微服务名会变成unable

#配置eureka服务端的相关属性
eureka:
  client:
    #配置eureka的注册地址  (defaultZone没有提示,必须手写)
    service-url:
      defaultZone: http://eureka1:20001/eureka,http://eureka2:20002/eureka,http://eureka3:20003/eureka
    #配置当前微服务是否(注册)到注册中心的服务
    register-with-eureka: false
    #配置当前微服务是否(抓取)注册中心的微服务 (当前微服务就是注册中心,不做抓取微服务的功能,所以改配置成false;)
    fetch-registry: false